---
name: Deploy para o GCP
on:
  push:
    branches: [ main ]
jobs:
  build-push-gar:
    name: Gerando a imagem e enviando ao artifact registry
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: hello-cicd
      PROJECT_ID: ci-cd-394523
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true

    - name: Buildar a imagem docker
      run: docker build -t $IMAGE_NAME:latest .

    - name: Autentica o docker no GCP
      run: |-
        gcloud auth configure-docker us-east4-docker.pkg.dev -y

    - name: Fazendo Push da imagem para o Artifact Registry
      env:
        GIT_TAG: v0.1.0
      run: |-
        docker tag $IMAGE_NAME:latest us-east4-docker.pkg.dev/$PROJECT_ID/$IMAGE_NAME:latest
        docker tag $IMAGE_NAME:latest us-east4-docker.pkg.dev/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
        docker push us-east4-docker.pkg.dev/$PROJECT_ID/$IMAGE_NAME:latest
        docker push us-east4-docker.pkg.dev/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG



