name: CI-CD Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: meu-projeto-394802
  REGION: us-east4
  REPO_NAME: hello-cicd

jobs:
  build-and-deploy:
    name: Configuração, Build e Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: "auth"
        name: Autenticando no google-cloud
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT }}"

      - name: Configurando o SDK do google-cloud
        uses: google-github-actions/setup-gcloud@v0

      - name: Autenticando o Docker
        run: gcloud auth configure-docker us-east4-docker.pkg.dev

      - name: Fazendo build e criando tag para a imagem
        run: |-
          docker build -t us-east4-docker.pkg.dev/${{ env.PROJECT_ID }}/repo/hello:latest .

      - name: Enviando a imagem para o Artifact Registry
        run: |-
          docker push us-east4-docker.pkg.dev/${{ env.PROJECT_ID }}/repo/hello:latest

      - name: Fazendo Deploy no Cloud Run
        run: |-
          gcloud run deploy teste \
          --region $REGION \
          --image us-east4-docker.pkg.dev/${{ env.PROJECT_ID }}/repo/hello:latest \
          --allow-unauthenticated \
          --platform "managed" \
          --quiet
