name: Deploy para o GCP
on:
  push:
    branches: [ main ]
jobs:
  ci-gcp:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        project_id: ${{ secrets.PROJECT_ID }}
        export_default_credentials: true

    - name: Autentica o docker no GCP
      run: |-
        gcloud auth configure-docker ${{ secrects.ARTIFACT_REGISTRY_REGION }}-docker.pkg.dev

    - name: Buildando a imagem e fazendo Push da imagem para o Artifact Registry
      env:
        GIT_TAG: v0.1.0
      run: |-
        docker build -t ${{ secrects.ARTIFACT_REGISTRY_REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.REPOSITORY }}/${{ secrets.IMAGE_NAME }}:latest .
        docker push ${{ secrects.ARTIFACT_REGISTRY_REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.REPOSITORY }}/${{ secrets.IMAGE_NAME }}:latest