name: Deploy para o GCP
on:
  push:
    branches: [ main ]
jobs:
  ci-gcp:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ci-cd-394523
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true

    - id: 'auth'
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0.4.0
      with:
        workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
        service_account: 'gitactions@ci-cd-394523.iam.gserviceaccount.com'

    - name: Autentica o docker no GCP
      run: |-
        gcloud auth configure-docker us-east4-docker.pkg.dev

    - name: Buildando a imagem e fazendo Push da imagem para o Artifact Registry
      env:
        GIT_TAG: v0.1.0
      run: |-
        docker build -t us-east4-docker.pkg.dev/ci-cd-394523/hello-cicd/hello:latest .
        docker push us-east4-docker.pkg.dev/ci-cd-394523/hello-cicd/hello:latest
    
    - name: Deploy Docker image
      run: gcloud run deploy hellohaha --image hello:latest --region us-east4 --memory 128Mi --min-instances 0 --max-instances 1 --platform managed --port 80 --allow-unauthenticated