name: Deploy para o GCP
on:
  push:
    branches: [ main ]
jobs:
  ci-gcp:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: hello-cicd
      PROJECT_ID: ci-cd-394523
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true

    - name: Autentica o docker no GCP
      run: |-
        gcloud auth configure-docker us-east4-docker.pkg.dev

    - name: Buildando a imagem e fazendo Push da imagem para o Artifact Registry
      env:
        GIT_TAG: v0.1.0
      run: |-
        docker build -t us-east4-docker.pkg.dev/ci-cd-394523/hello-cicd/hello:latest .
        docker push us-east4-docker.pkg.dev/ci-cd-394523/hello-cicd/hello:latest