name: Deploy Nginx

on:
  push:
    branches:
    - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: code checkout
      uses: actions/checkout@v2

    - name: install the gcloud cli
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ci-cd-394523
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        export_default_credentials: true

    - name: build and push the docker image
      env:
        GOOGLE_PROJECT: ci-cd-394523
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.devgcloud auth configure-docker us-east4-docker.pkg.dev
        docker build -t us-east4-docker.pkg.dev/ci-cd-394523/hello-cicd:latest .
        docker push us-east4-docker.pkg.dev/ci-cd-394523/hello-cicd:latest



