# name: Deploy para o GCP
# on:
#   push:
#     branches: [ main ]
# jobs:
#   ci-gcp:
#     runs-on: ubuntu-latest
#     env:
#       PROJECT_ID: ci-cd-394523
#     steps:

#     - name: Checkout
#       uses: actions/checkout@v2

#     - uses: google-github-actions/setup-gcloud@v0
#       with:
#         service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
#         project_id: ${{ env.PROJECT_ID }}
#         export_default_credentials: true

#     - name: Autentica o docker no GCP
#       run: |-
#         gcloud auth configure-docker us-east4-docker.pkg.dev

#     - name: Buildando a imagem e fazendo Push da imagem para o Artifact Registry
#       env:
#         GIT_TAG: v0.1.0
#       run: |-
#         docker build -t us-east4-docker.pkg.dev/ci-cd-394523/hello-cicd/hello:latest .
#         docker push us-east4-docker.pkg.dev/ci-cd-394523/hello-cicd/hello:latest
    
#     - name: Deploy Docker image
#       run: gcloud run deploy hellohaha --image hello:latest --region us-east4 --memory 128Mi --min-instances 0 --max-instances 1 --platform managed --port 80 --allow-unauthenticated
name: nextjs-cloud-run

on:
  push:
    branches:
      - master
      - main

env:
  PROJECT_ID: ci-cd-394523
  REGION: us-east4
  # project-name but it can be anything you want
  REPO_NAME: hello-cicd

jobs:
  build-and-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Authenticate with Google Cloud
      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT }}"

      # Setup gcloud CLI/SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Authorize Docker push
        run: gcloud auth configure-docker us-east4-docker.pkg.dev

      - name: Build and tag the docker image
        run: |-
          docker build -t us-east4-docker.pkg.dev/ci-cd-394523/hello-cicd/hello:latest .

      - name: Push the image to the Google Container Registry (GCR)
        run: |-
          docker push us-east4-docker.pkg.dev/ci-cd-394523/hello-cicd/hello:latest

      - name: Deploy
        run: |-
          gcloud run deploy teste \
          --region $REGION \
          --image us-east4-docker.pkg.dev/ci-cd-394523/hello-cicd/hello:latest \
          --platform "managed" \
          --quiet
